/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:25a87986-d67f-4636-860a-b7cdc2b0c83d",
    "aws_cognito_region": "us-east-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "86cfbe5e93c44114b5ea8b6435616c39",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
