/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e136ad44-a696-484c-9c11-9e97b6ddbaa7",
    "aws_cognito_region": "us-east-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "d0599af832fd48b2992ef9766fa8162e",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
